//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioOfMunshiFaysalAhmed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_msg
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Enter Your Name")]
        [Display(Name = "Enter Name")]
        public string name { get; set; }
        [Required(ErrorMessage = "Enter Your Email")]
        [Display(Name = "Enter Email")]
        [EmailAddress(ErrorMessage ="Please Enter a Valid Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Enter Your Subject")]
        [Display(Name = "Enter Subject")]
        public string subject { get; set; }
        [Required(ErrorMessage = "Enter Your Message")]
        [Display(Name = "Enter Message")]
        public string message { get; set; }
    }
}
